highlighter: pygments

gems:
  - jekyll-sitemap

sass:
  style: :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: notes
    values:
      layout: page


exclude: ['Gemfile', 'Gemfile.lock', 'CNAME', 'vendor', 'bin', 'resume', 'tmp']
