[build]
  command = "npm run build"
  publish = "build/"

[build.environment]
  NODE_VERSION = "17.2.0"
  NPM_FLAGS = "--version"

[[headers]]
  for = '/photos/rss'
  [headers.values]
    Content-Type = "application/rss+xml"
